parameters:
# Здесь могут быть параметры бандла
  panelMenuTemplate: "@@FlexyAdminFrame/panelmenu.html.twig"
  uploads_path: '/public/uploads/embedded'

services:

  # Конфигурация для всех сервисов  этого файла по умолчанию
  _defaults:
    autowire: true
    autoconfigure: true


  # Регистрируем контроллеры бандла и репозиторий как DI-сервисы
  flexycms\FlexyAdminFrameBundle\Controller\AdminBaseController: ~

  flexycms\FlexyAdminFrameBundle\Services\PanelMenuGenerator:
    calls:
      - setInjection: [ 'Symfony\Component\Routing\Generator\UrlGeneratorInterface', 'flexycms\FlexyArticlesBundle\Repository\ArticleCategoryRepository' ]


  flexyadminframe_modules_route_loader:
    class: flexycms\FlexyAdminFrameBundle\Services\ModulesRouteLoader
    autowire: true
    autoconfigure: true
    tags: [routing.loader]



